# Generated by Django 2.2.24 on 2022-10-23 06:05

from django.db import migrations
import phonenumbers


def validate_numbers(apps, schema_editor):
    Flat = apps.get_model("property", "Flat")
    for flat in Flat.objects.all():
        number = phonenumbers.parse(flat.owners_phonenumber, "RU")
        flat.owners_pure_phone = phonenumbers.format_number(number, phonenumbers.PhoneNumberFormat.E164)
        flat.save()


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0005_auto_20221023_0831'),
    ]

    operations = [
        migrations.RunPython(validate_numbers)
    ]
