# Generated by Django 2.2.24 on 2022-10-23 06:05

import phonenumbers
from django.db import migrations


def validate_numbers(apps, schema_editor):
    Flat = apps.get_model("property", "Flat")
    flats = Flat.objects.all()
    for flat in flats.iterator():
        number = phonenumbers.parse(flat.owners_phonenumber, "RU")
        if phonenumbers.is_valid_number(number):
            flat.owners_pure_phone = phonenumbers.format_number(number, phonenumbers.PhoneNumberFormat.E164)
        else:
            flat.owners_pure_phone = None
        flat.save()


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0005_auto_20221023_0831'),
    ]

    operations = [
        migrations.RunPython(validate_numbers)
    ]
