# Generated by Django 2.2.24 on 2022-10-29 12:49

from django.db import migrations


def get_owners_data(apps, schema_editor):
    flats = apps.get_model("property", "Flat")
    owners = apps.get_model("property", "Owner")
    for flat in flats.objects.all():
        owners.objects.get_or_create(
            full_name=flat.owner,
            phone_number=flat.owners_phonenumber,
            normalized_number=flat.owners_pure_phone,
        )


class Migration(migrations.Migration):
    dependencies = [
        ('property', '0007_auto_20221029_1539'),
    ]

    operations = [
        migrations.RunPython(get_owners_data)
    ]
